Update templates.json
svelte-society/sveltesociety.dev pull request #251
Opened 2022-03-13 11:55 UTC by ln-dev7

Added a web application that retrieves information from a GitHub profile

2022-03-13 12:54 UTC, ln-dev7 reviewed
edit npm: ""

2022-03-13 20:14 UTC, MacFJA commented on src/routes/templates/templates.json
> +    		"npm": "npm run dev",
The data behind his key is the package name, not the command to run.

For a template, the `npm` key don't have a lot of meaning thought

2022-03-13 21:34 UTC, MacFJA requested changes

2022-03-13 21:34 UTC, MacFJA commented on src/routes/templates/templates.json
> +    		"title": "svelte-app",
`svelte-app` is a bit too generic for a template name.

I believe that (almost) all templates are for building an app, so they all are a "Svelte App".

Can you choose a name that better describe your template ?

2022-04-12 16:12 UTC, benmccann commented
closing due to lack of response

2022-04-12 16:12 UTC, closed without merging