Add @mavthedev/svodals
svelte-society/sveltesociety.dev pull request #279
Opened 2022-07-08 02:16 UTC by mavthedev

2022-07-08 23:58 UTC, mavthedev commented
uhh

2022-07-08 23:58 UTC, mavthedev commented
...

2022-07-09 16:14 UTC, MacFJA commented
Is it a tool or a component ?

From what I read from your code/example it look more like a new component than a development/building tool.

2022-07-10 14:42 UTC, mavthedev commented
im kind of indecisive on if its a component or tool since it is a mix of both. I'll put component tho

2022-07-10 14:47 UTC, mavthedev commented
wait a minute... didn't you make one of the modules i use?

2022-07-24 18:22 UTC, MacFJA requested changes

2022-07-24 18:22 UTC, MacFJA commented on src/routes/components/components.json
> +	}
There is a tabulation at the end of the line
```suggestion
	}
```

2023-12-16 13:25 UTC, lachlancollins approved these changes

2023-12-16 13:25 UTC, merged

2023-12-16 14:59 UTC, chadulous commented
does this package even still work lol