Add svelte-switch-case
svelte-society/sveltesociety.dev pull request #286
Opened 2022-07-25 20:49 UTC by l-portet

2022-08-13 19:12 UTC, MacFJA commented
Hello,

Your PR is in conflict with `staging`.

2022-08-13 22:32 UTC, MacFJA requested changes
You can run `npm run format` to fix all those errors

2022-08-13 22:32 UTC, MacFJA commented on src/routes/components/components.json
> +    		"title": "svelte-switch-case",
There are spaces instead of a tabulation
```suggestion
		"title": "svelte-switch-case",
```

2022-08-13 22:32 UTC, MacFJA commented on src/routes/components/components.json
> +    		"stars": 47
There are spaces instead of a tabulation
```suggestion
		"stars": 47
```

2022-08-13 22:32 UTC, MacFJA commented on src/routes/components/components.json
> +  	}
There are unnecessary spaces
```suggestion
	}
```

2022-08-13 22:32 UTC, MacFJA commented on src/routes/components/components.json
> +  	{
There are unnecessary spaces
```suggestion
	{
```

2022-08-14 08:33 UTC, l-portet commented
Thanks, it should be cleaned now.

2022-08-14 10:09 UTC, MacFJA approved these changes

2022-08-14 10:09 UTC, merged