Added `virtue-ui` to `packages.json`
svelte-society/sveltesociety.dev pull request #593
Opened 2024-02-25 11:17 UTC by leonardodipace

## 🎯 Changes

Added `virtue-ui` to `packages.json`

## ✅ Checklist

- [x] I have given my PR a descriptive title
- [x] I have run `pnpm run lint` locally on my changes

2024-02-25 12:09 UTC, lachlancollins requested changes

2024-02-25 12:09 UTC, lachlancollins commented on src/routes/packages/packages.json
> +			"official",
Hi @leonardodipace , the official tag is for packages released by the Svelte team.

2024-02-25 12:12 UTC, leonardodipace commented on src/routes/packages/packages.json
> +			"official",
Hi @lachlancollins, I removed the official tag, thank you!

2024-02-26 08:05 UTC, lachlancollins approved these changes

2024-02-26 08:05 UTC, merged